version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/models:/root/.ollama/models
    networks:
      - net
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - net
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    networks:
      - net

networks:
  net: